# Grantmaker settings
foundation_name: J.R. Albert Foundation
foundation_tagline: Promoting healthy living and wellness
email_public: staff@jralbertfoundation.org
grant_application_login: https://www.grantinterface.com/Common/LogOn.aspx?eqs=kw_r9STKgaXCIWXbdFWB9tE44mEel3TwmvqLoCzs9JQ1

# Social media settings
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
twitter: 
facebook: 
instagram: 
github: 

# Site settings
# Meta tags
title: # Default's to foundation_name if left blank
description: > # this means to start on the next line (which needs to be indented two spaces)"
  J. R. Albert was interested in promoting healthy living and wellness, and hoped that the growing prevalence of obesity-related diseases and their effects on quality of life could be prevented whenever possible.

# Google settings
live: false # switch to true when you're ready for the site to be indexed by Google and other web crawlers

# Jekyll settings
collections:
  featured-cards:
    output: true
  recent-grants:
    output: true
sass:
    sass_dir: css/_sass
baseurl: "/jraf" # Leave this blank unless your site is located on a subpath, e.g. /blog
url: "http://grantmakers.github.io" # Typically http://www.yourdomain.org


# Build settings
exclude: 
  - README.md
  - /images/photoshop-helpers
